### ISSUE TITLE
Game repetitively ends once finished

### ISSUE THREAD

**Issue by TheMysterys** [jaylawl/Jaygrounds#11]
**Describe the bug**
Finish a round of golf and the server will constantly post the end game message till the server removes you from the game or you leave

**To Reproduce**
1. Play a round of golf
2. Finish the last hole
3. Watch the chaos

**Expected behavior**
One single message to be sent when ending

**Screenshots**
http://cdn.themysterys.com/vQoCLCSo

**Additional context**
Big Bug

**Comment by jaylawl** [comment]
looooooooooooooooooooooooooooool

**Comment by jaylawl** [comment]
fixed tho (in pending update)
